#cloud-config

mounts:
  - [swap, null]

users:
  - name: tom
    groups: [sudo]
    shell: "/bin/bash"
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:tomruttle
    lock_passwd: true

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    kubernetes.list:
      source: deb [arch=amd64] https://apt.kubernetes.io kubernetes-xenial main
      keyid: 7F92E05B31093BEF5A3C2D38FEEA9169307EA071

package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - software-properties-common
  - bridge-utils
  - lsb-release
  - ethtool
  - socat
  - ebtables
  - conntrack
  - libnetfilter-conntrack3
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - kubelet
  - kubeadm
  - kubectl
  - kubernetes-cni
  - cri-tools

write_files:
  - path: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
      ip_tables
      overlay
 
  - path: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

  - path: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }

power_state:
  mode: reboot

runcmd:
  - sed -ri '/\sswap\s/s/^#?/#/' /etc/fstab
  - sudo apt-mark hold kubelet kubeadm kubectl
  - sudo apt-get autoremove
