apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: 192.168.11.1
        peer-asn: 65002
        my-asn: 65011
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 192.168.11.128/25