apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: tom
spec:
  groups:
  - system:authenticated
  request: {{ base64_encoded_csr }}
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
