apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.13.10
skipPhases:
  - addon/kube-proxy
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 192.168.13.10
  taints: null
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: 192.168.11.100
kubernetesVersion: 1.23.0
networking:
  serviceSubnet: "10.96.0.0/16"
apiServer:
  extraArgs:
    feature-gates: "MixedProtocolLBService=true"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd