apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    feature-gates: "MixedProtocolLBService=true"
    node-ip: 192.168.13.12
  taints: null
controlPlane:
  localAPIEndpoint:
    advertiseAddress: 192.168.13.12
  certificateKey: {{ certificate-key }}
discovery:
  bootstrapToken:
    token: {{ token }}
    apiServerEndpoint: "192.168.11.100:6443"
    caCertHashes: [{{ discovery-token-ca-cert-hash }}]
