apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tom@ruttle.net
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: tom@tomruttle.com
          apiTokenSecretRef:
            name: cloudflare-api-token-letsencrypt-prod
            key: api-token
