apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ruttle-net-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: cilium
  defaultBackend:
    service:
      name: nginx-test
      port:
        number: 80    
  tls:
  - hosts:
    - www.ruttle.net
    - ruttle.net
    secretName: wildcard-certificate
