apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-staging
  namespace: cert-manager
spec:
  secretName: wildcard-staging-certificate
  issuerRef:
    name: letsencrypt-staging
  dnsNames:
  - '*.ruttle.net'
  - ruttle.net
